### PR TITLE
created version 2.0

### PR DESCRIPTION
**Pull request by Chiranjeev-droid**
Updated UI Design of home page

### CODE REVIEW

**Comment by praveenscience** [comment]
Seems like a copy of this: [Meet Shah](https://meet7202.github.io/). Plagiarism cannot be accepted. 😓

Would you like to explain anything?

**Comment by Chiranjeev-droid** [comment]
> Seems like a copy of this: [Meet Shah](https://meet7202.github.io/). Plagiarism cannot be accepted. 😓
> 
> Would you like to explain anything?

Yes . Is there any plagiarism in github because I think github is made for open source contributions and what I think is that we can take the code from github and use it as per our need. So what is wrong in that and by the way what is plagiarism in coding, we all are using same syntax, same boiler plate template, etc
   


So can you please explain is there any plagiarism thing exist in github and if yes then explain me

**Comment by praveenscience** [comment]
Taking inspiration and doing something is totally different from outrightly ripping off from the efforts of another person's hard work. That's plagiarism.

What about me copying the code of Facebook (where I was working) and put it on GitHub and say Open Source is love. Do you think Facebook will be happy and not sue me? 😓

[Is copying code from GitHub plagiarism? - Quora](https://www.quora.com/Is-copying-code-from-GitHub-plagiarism)

**Comment by eync** [comment]
If code or project is released in github without license (which the original repo doesn't have), it doesn't make it by default "free to use, contribute or redistribute".

Read more at: [If a repository has no license...](https://opensource.stackexchange.com/a/1721)

**Pull request closed without merging**
